### ISSUE TITLE
Should we deprecate this module since importing with `npm:mongodb` is working well with Deno?

### ISSUE THREAD

**Issue by erfanium** [denodrivers/mongo#380]

**Comment by lucsoft** [comment]
I would love a hybrid version were we would use npm as a default but also webify the interfaces nodejs brings

**Comment by erfanium** [comment]
We can publish a new module on npm like mongodb-webified. It can benfites both worlds

**Comment by steverandy** [comment]
Can you share how did you get the `npm:mongodb` to work?

I got similar error to this issue: https://github.com/denoland/deno/issues/15798 when I tried using `npm:mongodb` in a `fresh` project.
`error: Uncaught (in promise) Error: Cannot find module 'crypto'`

**Comment by erfanium** [comment]
```ts
import { MongoClient } from "npm:mongodb";

const client = new MongoClient("mongodb://localhost:27017/test");
await client.connect();
console.log("Connected");

console.log(await client.db().collection("test").findOne());

```

cmd:
```sh
deno run -A --unstable main.ts
```

**Comment by steverandy** [comment]
Interesting. When I tried the script above it works.

But when tried using it in `fresh` app got the following error:

```
error: Uncaught (in promise) Error: Cannot find module 'crypto'
Require stack:
- /Users/steve/Library/Caches/deno/npm/registry.npmjs.org/mongodb/4.10.0/lib/operations/add_user.js
- /Users/steve/Library/Caches/deno/npm/registry.npmjs.org/mongodb/4.10.0/lib/admin.js
- /Users/steve/Library/Caches/deno/npm/registry.npmjs.org/mongodb/4.10.0/lib/index.js
- /Users/steve/Library/Caches/deno/npm/registry.npmjs.org/mongodb/4.10.0/lib/index.js
    at Function.Module._resolveFilename (deno:ext/node/02_require.js:615:17)
    at Function.Module._load (deno:ext/node/02_require.js:447:29)
    at Module.require (deno:ext/node/02_require.js:658:21)
    at require (deno:ext/node/02_require.js:789:18)
    at Object.<anonymous> (file:///Users/steve/Library/Caches/deno/npm/registry.npmjs.org/mongodb/4.10.0/lib/operations/add_user.js:4:16)
    at Object.<anonymous> (file:///Users/steve/Library/Caches/deno/npm/registry.npmjs.org/mongodb/4.10.0/lib/operations/add_user.js:73:4)
    at Module._compile (deno:ext/node/02_require.js:719:36)
    at Object.Module._extensions..js (deno:ext/node/02_require.js:752:12)
    at Module.load (deno:ext/node/02_require.js:636:34)
    at Function.Module._load (deno:ext/node/02_require.js:493:14)
```

**Comment by erfanium** [comment]
@steverandy please report it on fresh github repo. Thanks
Not related to this issue

**Comment by lucsoft** [comment]
> We can publish a new module on npm like mongodb-webified. It can benfites both worlds

i prefer that it stays here. Else people could be thinking that it's not really made for Deno.

**Comment by josephrocca** [comment]
I just tried the `npm:` version and it for some reason it hung 90% of the time and never connected (no error thrown).

```js
const client = new MongoClient(`mongodb://${user}:${pass}@${ip}:${port}/${dbName}`);
await client.connect();
db = client.db(dbName);
```

Strange that it works sometimes. Seems premature to deprecate this unless I'm making some sort of weird mistake there, but that seems like a good idea in the long run - if only to have consistency of the API between Node and Deno.

**Comment by vorticalbox** [comment]
You can follow the issues with mongoose/mongodb with deno here

https://github.com/denoland/deno/issues/15824

**Comment by jtoppine** [comment]
Well, since this issue is in question format, might as well give my 2 cents.

It would be sad to see "native" deno mongo driver go, or fall into disrepair. Deno driver has the potential to be cleaner, prettier and faster, and the npm compatibility layer is big, complex and slow-ish to load.

It seems to also be true that there is a lack of maintainers to keep working on the Deno driver. And that it needs nontrivial amount of work to be good enough for widespread production use. Since the userbase is small for now, and the node driver is usable already as-is, it may be unrewarding to work on the Deno driver.

Maybe the best solution for now would be to put a big banner on the readme, with:

- "call for maintainers" 
-  a note about the deno driver being alpha/beta quality, maybe detailing some of the most important missing features (automatic reconnect etc)
-  a note to suggest regular users may want to use the NPM driver (for now)

This way regular users would not be discouraged from using Deno because of frustrating problems with unstable drivers. And there would be hope for the project to gain maintainers in the future, or even some "official" support from Mongo, eventually improving the driver beyond the NPM driver :)

**Comment by ThePotatoChronicler** [comment]
@erfanium The compatibility is not quite there yet: https://github.com/denoland/deno/issues/16633

**Comment by denizdogan** [comment]
> @erfanium The compatibility is not quite there yet: [denoland/deno#16633](https://github.com/denoland/deno/issues/16633)

This has supposedly been fixed in Deno 1.37!

**Comment by fro-profesional** [comment]
I jus tried on local an deploy and seems to be working with MongoDB Atlas serverless

```ts
import { MongoClient } from "npm:mongodb"
import { ulid } from "https://deno.land/std@0.202.0/ulid/mod.ts";

const client = new MongoClient("<url>")

client.connect();

Deno.serve(async () => {

  const data = await client.db("deno").collection("deno").insertOne({
    name: ulid()
  })

  return new Response(JSON.stringify({
    data
  }), {
    headers: { "Content-Type": "application/json" },
  })
})

```

**Comment by alexbevi** [comment]
Hey all, just wanted to chime in here as I'm the Product Manager at MongoDB for the Node.js driver, as well as the reporter of https://github.com/denoland/deno/issues/16633 (which was addressed directly in the driver, as well as in the runtime via https://github.com/denoland/deno/pull/20314).

Ultimately the goal is to have an ideal, runtime agnostic driver that the community can use so if there are still issues with using the driver via Deno I'd love to hear them :)

**Comment by lucsoft** [comment]
@alexbevi Would be cool if the Node.js driver would be Webified and uses modern standard. Same as what happened with BSON which is almost Node.js free which is awesome. My dream would be that the deno/nodejs driver could be the same code and only need to polyfill the [Direct Sockets API](https://wicg.github.io/direct-sockets/) :D (and maybe in the future not even that)

**Comment by alexbevi** [comment]
Thanks for the feedback @lucsoft. We're currently evaluating the driver against Deno to see if there's anything that outright doesn't work (feel free to share if you're aware of features that don't work)

**Comment by erfanium** [comment]
@alexbevi Thanks for reaching out to us! As far as I know, MongoDB's official driver for Node.js only ships with CJS modules. So, you'd need to use Deno's npm compatibility layer to use the official driver.

I'd love to see MongoDB's official driver shipped as a Deno-native package in the deno.land/x registry, just like this module. with no dependency to `std/node`

**Comment by DanCuatro** [comment]
I tried this example: 

```ts
import { MongoClient } from "npm:mongodb"
import { ulid } from "https://deno.land/std@0.202.0/ulid/mod.ts";

const client = new MongoClient("<url>")

client.connect();

Deno.serve(async () => {

  const data = await client.db("deno").collection("deno").insertOne({
    name: ulid()
  })

  return new Response(JSON.stringify({
    data
  }), {
    headers: { "Content-Type": "application/json" },
  })
})
```
and it failed with followin error:

```
MongoPoolClosedError: Attempted to check out a connection from closed connection pool
    at ConnectionPool.processWaitQueue (file:///C:/Users/Dan%20Cuatro/AppData/Local/deno/npm/registry.npmjs.org/mongodb/6.1.0/lib/cmap/connection_pool.js:520:45)
    at ConnectionPool.close (file:///C:/Users/Dan%20Cuatro/AppData/Local/deno/npm/registry.npmjs.org/mongodb/6.1.0/lib/cmap/connection_pool.js:284:14)
    at Server.destroy (file:///C:/Users/Dan%20Cuatro/AppData/Local/deno/npm/registry.npmjs.org/mongodb/6.1.0/lib/sdam/server.js:130:19)
    at destroyServer (file:///C:/Users/Dan%20Cuatro/AppData/Local/deno/npm/registry.npmjs.org/mongodb/6.1.0/lib/sdam/topology.js:409:12)
    at ext:deno_node/internal/util.mjs:93:15
    at new Promise (<anonymous>)
    at destroyServer (ext:deno_node/internal/util.mjs:78:12)
    at file:///C:/Users/Dan%20Cuatro/AppData/Local/deno/npm/registry.npmjs.org/mongodb/6.1.0/lib/sdam/topology.js:212:56
    at Function.from (<anonymous>)
    at Topology.close (file:///C:/Users/Dan%20Cuatro/AppData/Local/deno/npm/registry.npmjs.org/mongodb/6.1.0/lib/sdam/topology.js:211:40) {
  address: "ac-el7mrgl-lb.ks3woph.mongodb.net.:27017",
  [Symbol(errorLabels)]: Set(0) {}
}
error: Uncaught (in promise) MongoNetworkTimeoutError: connection timed out
    at connectionFailureError (file:///C:/Users/Dan%20Cuatro/AppData/Local/deno/npm/registry.npmjs.org/mongodb/6.1.0/lib/cmap/connect.js:381:20)
    at TLSSocket.<anonymous> (file:///C:/Users/Dan%20Cuatro/AppData/Local/deno/npm/registry.npmjs.org/mongodb/6.1.0/lib/cmap/connect.js:285:22)
    at Object.onceWrapper (ext:deno_node/_stream.mjs:1927:32)
    at TLSSocket.emit (ext:deno_node/_stream.mjs:1852:9)
    at TLSSocket._onTimeout (node:net:848:10)
    at cb (ext:deno_node/internal/timers.mjs:63:31)
    at Object.action (ext:deno_web/02_timers.js:151:11)
    at handleTimerMacrotask (ext:deno_web/02_timers.js:65:10)
    at eventLoopTick (ext:core/01_core.js:189:21)
Watcher Process failed. Restarting on file change...
```

Im on Windows 11 Home 22H

```
deno 1.37.1 (release, x86_64-pc-windows-msvc)
v8 11.8.172.6
typescript 5.2.2
```

With MongoDB Atlas serverless

**Comment by lucsoft** [comment]
We need to start to differentiate. if you use Atlas use the Atlas SDK. Atlas is not MongoDB, its Atlas.

**Comment by JWhist** [comment]
FWIW i was able to get the regular mongo driver working on Netlify edge functions by using an older version, without the dependency on the newer web-bson package.  Version 0.31.1 worked for me, however the newer versions had a problem imported that dependency.

**Comment by softbeehive** [comment]
> We need to start to differentiate. if you use Atlas use the Atlas SDK. Atlas is not MongoDB, its Atlas.

Mongo Atlas deprecated Data API
https://www.mongodb.com/docs/atlas/app-services/deprecation/#std-label-app-services-deprecation

I guess by using Atlas for production you risk being forced into costly migration when they shut it down completely

**Comment by dwstevens** [comment]
Also adding my 0.02, FWIW, I think deno has an opportunity to move into an Elixir like space for Typescript, and has already started down that road with std lib / jsr. I’d like to see first class std lib type support for the major DBs.

**Comment by jonseppanen** [comment]
It seems like the deno imported npm library for mongo does not support unix domain sockets - is this expected behaviour or an oversight?
Where is the correct place to raise such an issue? It seems like it would be more on the deno/npm side but it kinda crosses boundaries.
