### ISSUE TITLE
Is this module working with DocumentDB

### ISSUE THREAD

**Issue by AfMyte** [denodrivers/mongo#403]
Good morning folks, I am trying to use this module with DocumentDB but I always receive this error:

> Error: MongoError: "Connection failed: Cannot read properties of undefined (reading 'includes')"
>     at MongoClient.connect (file:///app/vendor/deno.land/x/mongo@v0.32.0/src/client.ts:46:13)
>     at connect (file:///app/src/utils/connection.js:15:18)
>     at session (file:///app/src/controllers/session.js:10:22)
>     at eventLoopTick (ext:core/01_core.js:183:11)
>     at async dispatch (file:///app/vendor/deno.land/x/oak@v12.5.0/middleware.ts:80:7)
>     at async dispatch (file:///app/vendor/deno.land/x/oak@v12.5.0/middleware.ts:80:7)
>     at async dispatch (file:///app/vendor/deno.land/x/oak@v12.5.0/middleware.ts:80:7)
>     at async cors (file:///app/vendor/deno.land/x/oak_cors@v0.1.1/src/cors.ts:204:5)
>     at async middleware (file:///app/vendor/deno.land/x/oak_cors@v0.1.1/src/cors.ts:243:5)
>     at async dispatch (file:///app/vendor/deno.land/x/oak@v12.5.0/middleware.ts:80:7)

That I think it is coming from here https://github.com/denodrivers/mongo/blob/main/src/utils/uri.ts#L42

**Comment by erfanium** [comment]
@AfMyte 
Haha, This module is not even working well with actual MongoDB. you may having a chance using npm/mongodb module

**Comment by erfanium** [comment]
@AfMyte 
I have never used AWS DocumentDB. You may test `npm:mongodb` package with Deno npm compat mode.
