### ISSUE TITLE
Error: MongoError: "Connection failed: Failed to decode base64"

### ISSUE THREAD

**Issue by unpin** [denodrivers/mongo#411]
After upgrading to mongo@v0.33.0, the connection consistently fails with the error "Connection failed: Failed to decode base64", occurring both locally and on Deno Deploy. I had to downgrade to mongo@v0.32.0 for now.

```ts
import { Database, MongoClient } from "mongo";

const DATABASE_URL = "mongodb+srv://<username>:<password>@<db_cluster_url>/<db_name>?authMechanism=SCRAM-SHA-1"

const client = new MongoClient();
await client.connect(DATABASE_URL);
```

**Comment by lucsoft** [comment]
Can you give more backstory? what db cluster is this? Atlas?


Do you have non base64 decodable chars in your string?

**Comment by erfanium** [comment]
I think it's related to #406

**Comment by gustawdaniel** [comment]
I have this for 0.33

```
AError connecting to MongoDB Error: MongoError: "Connection failed: Failed to decode base64"
    at MongoClient.connect (https://deno.land/x/mongo@v0.33.0/src/client.ts:63:13)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async getDb (file:///home/daniel/pro/matrix-aggregator-scraper/src/storage/mongo.ts:17:5)
    at async file:///home/daniel/pro/matrix-aggregator-scraper/db.ts:4:14
error: Uncaught (in promise) Error: MongoError: "Connection failed: Failed to decode base64"
      throw new MongoDriverError(`Connection failed: ${e.message || e}`);
            ^
    at MongoClient.connect (https://deno.land/x/mongo@v0.33.0/src/client.ts:63:13)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async getDb (file:///home/daniel/pro/matrix-aggregator-scraper/src/storage/mongo.ts:17:5)
    at async file:///home/daniel/pro/matrix-aggregator-scraper/db.ts:4:14
```

**Comment by barefoot-alien** [comment]
Has anyone found a fix for this?
