### ISSUE TITLE
error upgrade 0.32.0 > 0.33.0

### ISSUE THREAD

**Issue by damienmillet** [denodrivers/mongo#412]
Hi, 

this morning I decide to upgrade my dependencies of deno and mongo

| from | to |
| ------------- | ------------- |
| `std@0.214.0` | `std@0.224.0` |
| `mongo@v0.32.0` | `mongo@v0.33.0` |

now i hav an error : 

```
error: Uncaught (in promise) BSONError: corrupt object bson
        throw new BSONError('corrupt object bson');
```

I tried to downgrade to mongo@v0.32.0 and that fix the problem.

best regards,

DM

**Comment by erfanium** [comment]
cc @lucsoft

**Comment by lucsoft** [comment]
@damienmillet Do you use an old MongoDB version? 

bson had some breaking changes internally

**Comment by damienmillet** [comment]
> @damienmillet Do you use an old MongoDB version? 
> 
> 
> 
> bson had some breaking changes internally 

MongoDB 2.2.3

**Comment by lucsoft** [comment]
@damienmillet Can you check if your issue persists on 7.0.9?

**Comment by damienmillet** [comment]
i ll try it

**Comment by damienmillet** [comment]
same issue with 7.0.9

**Comment by the-abe-train** [comment]
+1 for this issue. Mongo version is 7.0.11, only seeing this error with 0.33.0. It happens when I do a `find` query, but not `findOne`.

**Comment by itning** [comment]
any update for this? I use v0.34.0 version have this issue also.

mongo version: mongo:8.0.6

**Comment by erfanium** [comment]
@itning Do you have any reproduction steps for this issue?

**Comment by itning** [comment]
> [@itning](https://github.com/itning) Do you have any reproduction steps for this issue?

It seems to be related to the content of the table data.

**but use mongo@v0.32.0 is normal**

```ts
import {
  MongoClient,
  ObjectId,
} from "https://deno.land/x/mongo@v0.34.0/mod.ts";

const client = new MongoClient();

await client.connect(
  "mongodb://root:root@nas.itning.cn:27017",
);

const database = client.database("cron");

interface WeiBoSchema {
  _id: ObjectId;
  time: Date;
  date: string;
  title: string;
  score: number;
  task_id: string;
}

const weibo = database.collection<WeiBoSchema>("weibo2");

const result = weibo.find({
  title: {
    $regex: /小米/,
    $options: "i",
  },
});
result.forEach((item) => {
  console.log(item);
});

```

```shell
deno.exe run --allow-net C:\Users\xx\WebstormProjects\dify_mongo\main.ts
Download ⣯ [00:00]
 - jsr:@lucsoft/web-bson/0.4.0/crypto                                                                                   







error: Uncaught (in promise) BSONError: corrupt object bson
        throw new BSONError('corrupt object bson');
              ^
    at deserializeObject (https://jsr.io/@lucsoft/web-bson/0.4.0/mod.js:3309:15)
    at deserializeObject (https://jsr.io/@lucsoft/web-bson/0.4.0/mod.js:3047:25)
    at deserializeObject (https://jsr.io/@lucsoft/web-bson/0.4.0/mod.js:3062:21)
    at deserializeObject (https://jsr.io/@lucsoft/web-bson/0.4.0/mod.js:3047:25)
    at internalDeserialize (https://jsr.io/@lucsoft/web-bson/0.4.0/mod.js:2910:12)
    at deserialize (https://jsr.io/@lucsoft/web-bson/0.4.0/mod.js:4396:12)
    at deserializeMessage (https://deno.land/x/mongo@v0.34.0/src/protocol/message.ts:117:24)
    at WireProtocol.receive (https://deno.land/x/mongo@v0.34.0/src/protocol/protocol.ts:126:23)
    at eventLoopTick (ext:core/01_core.js:178:7)

```

**Comment by lucsoft** [comment]
What mongo version are you using?

**Comment by itning** [comment]
> What mongo version are you using?

mongo:8.0.6

use v0.32.0 normal
